# Use, modification, and distribution are
# subject to the Boost Software License, Version 1.0. (See accompanying
# file LICENSE.txt)
#
# Copyright René Ferdinand Rivera Morell 2022.

name: "Installer: Windows"

on:
  push:
    branches: ["main", "release"]
    paths-ignore:
      [
        ".circleci/**",
        ".cirrus.yml",
        ".drone.star",
        ".semaphore/**",
        ".travis.yml",
        "appveyor.yml",
        "azure-pipelines.yml",
        ".ci/azp-*.yml",
      ]

jobs:
  wix:
    strategy:
      matrix:
        include:
          - { name: "Windows", image: "" }
    name: ${{ matrix.name }}
    runs-on: "windows-latest"
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
        with: { path: "b2" }
      - name: "Checkout"
        uses: actions/checkout@master
        with: { repository: "bfgroup/b2-pkg", path: "b2-pkg" }
      - name: "Install"
        run: |
          choco install vswhere
      - name: "Bootstrap"
        run: |
          cd "${env:GITHUB_WORKSPACE}/b2"
          ./bootstrap.bat
      - name: "Build"
        run: |
          cd "${env:GITHUB_WORKSPACE}/b2-pkg"
          "${env:GITHUB_WORKSPACE}/b2/b2.exe" --b2root="${env:GITHUB_WORKSPACE}/b2" windows
