# Copyright 2023 René Ferdinand Rivera Morell
# Use, modification, and distribution are subject to the
# Boost Software License, Version 1.0. (See accompanying file LICENSE.txt)

name: "Release: Archives"

on:
  # Allow manual runs.
  workflow_dispatch:
  # Run on publishing of releases.
  release: { types: [published] }
  # And run on pushes, for main and release branches.
  push:
    branches: ["main", "release", "version/*"]
    paths-ignore:
      [
        ".circleci/**",
        ".cirrus.yml",
        ".drone.star",
        ".semaphore/**",
        ".travis.yml",
        "appveyor.yml",
        "azure-pipelines.yml",
        ".ci/azp-*.yml",
      ]

jobs:
  archive:
    strategy:
      matrix:
        include:
          - { name: "Zip", format: "zip" }
          - { name: "7z", format: "7z" }
          - { name: "BZip2", format: "bzip2" }
          - { name: "Zstd", format: "zstd" }
    runs-on: ubuntu-latest
    name: ${{ matrix.name }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
        with: { path: "b2" }
      - name: "Git Archive"
        run: |
          cd "${{github.workspace}}/b2"
          version=`basename ${{github.ref_name}}`
          git archive --format=tar --output="${{github.workspace}}/b2-${version}.tar" "${{github.ref_name}}"
          cd "${{github.workspace}}"
          tar -xf "${{github.workspace}}/b2-${version}.tar"
          rm -rf "${{github.workspace}}/b2-${version}.tar"
      - name: "Zip Archive"
        if: ${{ matrix.format == 'zip' }}
        run: |
          cd "${{github.workspace}}"
          version=`basename ${{github.ref_name}}`
          zip -r -9 "${{github.workspace}}/b2-${version}.zip" "b2-${version}"
      - name: "7z Archive"
        if: ${{ matrix.format == '7z' }}
        run: |
          cd "${{github.workspace}}"
          version=`basename ${{github.ref_name}}`
          7za a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on "${{github.workspace}}/b2-${version}.7z" "b2-${version}"
      - name: "BZip2 Archive"
        if: ${{ matrix.format == 'bzip2' }}
        run: |
          cd "${{github.workspace}}"
          version=`basename ${{github.ref_name}}`
          tar -cv -j -f "${{github.workspace}}/b2-${version}.tar.bz2" "b2-${version}"
      - name: "Zstd Archive"
        if: ${{ matrix.format == 'zstd' }}
        run: |
          cd "${{github.workspace}}"
          version=`basename ${{github.ref_name}}`
          tar -cv --zstd -f "${{github.workspace}}/b2-${version}.tar.zstd" "b2-${version}"
      - name: "Cleanup"
        run: |
          cd "${{github.workspace}}"
          rm -rf "${{github.workspace}}/b2-${version}"
      - name: "Upload"
        uses: actions/upload-artifact@v3
        with:
          name: archives
          path: "${{github.workspace}}/b2-*"
      - name: "Publish"
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        with:
          files: "${{github.workspace}}/b2-*"
